kind: pipeline
name: default

steps:
# 代码分析
# - name: code-analysis
#   image: aosapps/drone-sonar-plugin
#   settings:
#     sonar_host:
#       from_secret: sonar_host
#     sonar_token:
#       from_secret: sonar_token

# 测试
- name: 代码测试
  image: python:3
  commands:
  - pip install -r requirements.txt

# 构建代码docker镜像
- name: 构建代码
  image: plugins/docker
  settings:
    registry: 
      from_secret: docker_registry
    repo: 
      from_secret: docker_repo
    username: 
      from_secret: docker_name
    password: 
      from_secret: docker_password
    tags:
      - latest
      - '1.0'

# 将部署文件放入指定目录
- name: 放入指定目录
  image: appleboy/drone-scp
  settings:
    host: 
      from_secret: ssh_host
    username: 
      from_secret: ssh_user
    port: 22
    password: 
      from_secret: ssh_password
    target: /www/wwwroot/api.test.huatian.fun/ci_test
    source: docker-compose.yaml

# 部署项目
- name: code-deploy
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_host
    username: 
      from_secret: ssh_user
    port: 22
    password: 
      from_secret: ssh_password
    script:
      - cd /www/wwwroot/api.test.huatian.fun/ci_test
      - docker-compose pull azumia/flask-restful-huatian
      - docker-compose up -d
  when:
    branch:
      - master