version: "2"
services:
  flask_app:
    image: flask-restful-huatian:latest
    container_name: flask-restful-huatian
    restart: always
    ports:
      - "75:80"
    volumes:
      - ./logs:/projects/logs
      - ./report:/projects/report
    links:
      - flask_redis

  flask_redis:
    image: redis:alpine
    container_name: flask_redis
    restart: always
